// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserSettings(t *testing.T) {
	t.Parallel()

	query := UserSettings()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserSettingsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSettingsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserSettings().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSettingsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserSettingSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSettingsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserSettingExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserSetting exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserSettingExists to return true, but got false.")
	}
}

func testUserSettingsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userSettingFound, err := FindUserSetting(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userSettingFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserSettingsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserSettings().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserSettingsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserSettings().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserSettingsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userSettingOne := &UserSetting{}
	userSettingTwo := &UserSetting{}
	if err = randomize.Struct(seed, userSettingOne, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}
	if err = randomize.Struct(seed, userSettingTwo, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userSettingOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userSettingTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserSettings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserSettingsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userSettingOne := &UserSetting{}
	userSettingTwo := &UserSetting{}
	if err = randomize.Struct(seed, userSettingOne, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}
	if err = randomize.Struct(seed, userSettingTwo, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userSettingOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userSettingTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testUserSettingsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserSettingsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userSettingColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserSettingToOneAccountUsingAccount(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserSetting
	var foreign Account

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, accountDBTypes, false, accountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Account struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.AccountID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Account().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserSettingSlice{&local}
	if err = local.L.LoadAccount(ctx, tx, false, (*[]*UserSetting)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Account == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Account = nil
	if err = local.L.LoadAccount(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Account == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserSettingToOneSetOpAccountUsingAccount(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserSetting
	var b, c Account

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userSettingDBTypes, false, strmangle.SetComplement(userSettingPrimaryKeyColumns, userSettingColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, accountDBTypes, false, strmangle.SetComplement(accountPrimaryKeyColumns, accountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, accountDBTypes, false, strmangle.SetComplement(accountPrimaryKeyColumns, accountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Account{&b, &c} {
		err = a.SetAccount(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Account != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserSettings[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.AccountID != x.ID {
			t.Error("foreign key was wrong value", a.AccountID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.AccountID))
		reflect.Indirect(reflect.ValueOf(&a.AccountID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.AccountID != x.ID {
			t.Error("foreign key was wrong value", a.AccountID, x.ID)
		}
	}
}

func testUserSettingsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserSettingsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserSettingSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserSettingsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserSettings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userSettingDBTypes = map[string]string{`ID`: `uuid`, `AccountID`: `character varying`, `ConfigKey`: `character varying`, `ConfigValue`: `character varying`}
	_                  = bytes.MinRead
)

func testUserSettingsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userSettingPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userSettingAllColumns) == len(userSettingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserSettingsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userSettingAllColumns) == len(userSettingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userSettingAllColumns, userSettingPrimaryKeyColumns) {
		fields = userSettingAllColumns
	} else {
		fields = strmangle.SetComplement(
			userSettingAllColumns,
			userSettingPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserSettingSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserSettingsUpsert(t *testing.T) {
	t.Parallel()

	if len(userSettingAllColumns) == len(userSettingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserSetting{}
	if err = randomize.Struct(seed, &o, userSettingDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserSetting: %s", err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userSettingDBTypes, false, userSettingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserSetting: %s", err)
	}

	count, err = UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
