[psql]
    dbname = "sonicflare"
    host = "localhost"
    user = "postgres"
    pass = ""
    sslmode = "disable"
    whitelist=[
        "account",
        "wallet",
        "daily_earning",
        "deposit",
        "withdrawal",
        "investment",
        "referral_payout",
        "notification",
        "user_setting",
        "login_info",
        "security_code"
    ]
